services:
 
  mysql:
    image: mysql:latest
    container_name: sacre-db
    environment:
      - MYSQL_ROOT_PASSWORD=dbssd@#
      - MYSQL_DATABASE=ssd_db
      - MYSQL_PASSWORD=dbssd@#
      - TZ=America/Sao_Paulo
    ports:
      - '3306:3306'
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - sacre
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppostgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 
networks:
  sacre:
    name: sacre
    external: true
 