# meu-nginx/nginx/site.conf
 
# Definição dos seus serviços de backend
upstream app {
    server sacre.app:8501;
}

# Configurações de SSL e Gzip movidas para o contexto 'server' ou mantidas no 'http' global
# As diretivas ssl_* podem ser globais se você incluir este arquivo dentro do bloco http
# ou específicas por servidor se colocadas dentro do bloco 'server'.
# Para simplificar, vamos colocar as comuns de SSL no bloco 'server'.
 
# Servidor para redirecionamento de HTTP para HTTPS
server {
    listen 80;
    server_name localhost;
 
    location / {
        return 301 https://$host$request_uri;
    }
}
 
# Servidor principal para tráfego HTTPS
server {
    listen 443 ssl;
    server_name localhost;
 
    # Define o root para os arquivos estáticos
    #root /var/www/maintenance;
 
    # Verifica se a página de manutenção existe
    # if (-f /var/www/maintenance/maintenance.html) {
    #     # Retorna 503 com a página de manutenção
    #     return 503;
    # }
 
    # # Página de erro para o status 503
    # error_page 503 @maintenance;
 
    # # Location para a página de manutenção
    # location @maintenance {
    #     # Reescreve a requisição para o arquivo de manutenção
    #     rewrite ^(.*)$ /maintenance.html break;
    # }
 
    # Configurações de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_session_cache shared:SSL:30m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
 
    # Caminhos dos certificados (verifique se correspondem à montagem no docker-compose)
    ssl_certificate /etc/nginx/ssl/sacre.ipt.br.crt;
    ssl_certificate_key /etc/nginx/ssl/sacre.ipt.br.key;
 
    # Configurações de Proxy
    client_max_body_size 100M;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
 
    # Configuração de Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss;
 
    # Rota padrão para o frontend
    location / {
        proxy_pass http://app;
        # Configurações cruciais para WebSocket
        proxy_http_version1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Aumentar o timeout para evitar que o Streamlit desconecte prematuramente
        proxy_read_timeout86400;
    }
 

}
 